### PR TITLE
Added Partially Complete Block API

### PR DESCRIPTION
**Pull request by Asbestosstar**
I was not sure how to implement the mixins, so you may want to fix those
Additionally, the Material + mapColor Provider Function constructors were giving me issues

### CODE REVIEW

**Comment by PseudoDistant** [comment]
Already
raphiAwau (585562521843531787)
?

**Comment by Asbestosstar** [comment]
What do you mean Already?

**Comment by PseudoDistant** [comment]
I mean that was speedy.
raphiDonutsu

**Comment by Asbestosstar** [comment]
Added Commands, though I am not good at commands (even leaving them out of my litlaunch clone so far) and many of the Quilt Libs were broken so some functions had to be left out. Though i just remembered you could extend interfaces with eachother so thats a plus

**Comment by Trinsdar** [comment]
@Asbestosstar Yo're gonna need to move the quilt api stuff to it's own separate module

**Comment by Trinsdar** [comment]
@Asbestosstar Yo're gonna need to move the quilt api stuff to it's own separate module

**Comment by Asbestosstar** [comment]
Ok check

**Comment by Trinsdar** [comment]
Closing this since this stuff is going in qtf

**Pull request closed without merging**
